package com.example.demo;

public class Authors {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authors.id
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authors.name
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authors.age
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authors.id
     *
     * @return the value of authors.id
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authors.id
     *
     * @param id the value for authors.id
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authors.name
     *
     * @return the value of authors.name
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authors.name
     *
     * @param name the value for authors.name
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authors.age
     *
     * @return the value of authors.age
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authors.age
     *
     * @param age the value for authors.age
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}