package com.example.demo;

public class Books {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.id
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.author_id
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    private Integer authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.title
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.id
     *
     * @return the value of books.id
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.id
     *
     * @param id the value for books.id
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.author_id
     *
     * @return the value of books.author_id
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.author_id
     *
     * @param authorId the value for books.author_id
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.title
     *
     * @return the value of books.title
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.title
     *
     * @param title the value for books.title
     *
     * @mbggenerated Thu Nov 25 04:51:07 JST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }
}